### PR TITLE
fix: replace panic with error in duplicate job name check

### LINKED ISSUE #6: checkDuplicateJobName panics instead of returning an error
### Area

Core API (App/Pipeline/Stage/Job)

### Problem or motivation

`job.go` uses `panic()` for duplicate job names. This is a user-facing validation error, not a programming bug.

### Proposed solution

Either return an error from `NewJob` (breaking API change) or add a validation pass in `app.Run()` / `app.Build()` that checks for duplicates and returns a proper error.

## Files

- `pkg/pisyn/job.go`

### Alternatives considered

_No response_

### PR DESCRIPTION
**Pull request by mvanhorn**
## Summary

`checkDuplicateJobName` now returns an `error` instead of calling `panic()`. The `App.Synth()` method runs a duplicate job name validation pass before synthesizing, so users get a clean error message instead of a stack trace.

## Changes

- `pkg/pisyn/job.go`: `checkDuplicateJobName` returns `error`. `NewJob` and `Clone` still panic on duplicates (preserves current API contract), but the error is now structured.
- `pkg/pisyn/app.go`: Added `checkDuplicateJobNames()` validation method. Called at the start of `Synth()` so duplicates are caught before any synthesis happens.
- `pkg/pisyn/app_test.go`: Added `TestSynthReturnsErrorForDuplicateJobNames` verifying that `Synth` returns a proper error and does not call the synthesizer.

## Why

Duplicate job names are a user-facing validation error, not a programming bug. Panicking crashes the process with a stack trace that obscures the actual problem. Returning an error from `Synth()` lets callers handle it gracefully.

The public API of `NewJob` and `Clone` stays unchanged (still returns `*Job`). The panic in those paths remains as a safety net for direct usage outside `Synth()`, but `Synth()` catches it first.

Fixes #6

This contribution was developed with AI assistance (Codex).

### CODE REVIEW

File: pkg/pisyn/app.go [hunk 1]
```diff
@@ -141,3 +144,18 @@ func platformsFromEnv() []string {
...
 	return out
 }
+
+func (a *App) checkDuplicateJobNames() error {
+	for _, p := range a.Pipelines() {
+		seen := map[string]bool{}
+		for _, st := range p.Stages() {
+			for _, j := range st.Jobs() {
+				if seen[j.JobName] {
+					return fmt.Errorf("pisyn: duplicate job name %q in pipeline %q", j.JobName, p.Construct.id)
```
Comment (t0st) [inline pkg/pisyn/app.go]:
```suggestion
					return fmt.Errorf("pisyn: duplicate job name %q in pipeline %q", j.JobName, p.Name)
```
The pipeline name fits better for a user-friendly message

File: pkg/pisyn/app.go [hunk 2]
```diff
@@ -47,6 +47,9 @@ func (a *App) Pipelines() []*Pipeline {
 
 // Synth synthesizes the app using the given synthesizer.
 func (a *App) Synth(s Synthesizer) error {
+	if err := a.checkDuplicateJobNames(); err != nil {
```
Comment (t0st) [inline pkg/pisyn/app.go]: Consider to move this into the Build() func as this gets called by Run() and Sync()

**Review by t0st — CHANGES_REQUESTED** [review]
Nice first PR — thx for the contribution!

Two suggestions:

1. Move the validation from Synth() to Build() — that way Run() catches duplicates before writing pipeline.json, and every code path gets it for free.
2. Use p.Name instead of p.Construct.id in the error message.

**Comment by mvanhorn** [comment]
Thanks @t0st - both addressed in 5932596:

1. Moved the duplicate-name check from `Synth()` to `Build()`. Now any path through `Run()` (default, build mode, or explicit `Synth`) hits it before `pipeline.json` gets written. Added `TestRunCatchesDuplicateBeforeWritingPipelineJSON` which verifies the error surfaces AND no `pipeline.json` is left on disk when validation fails.
2. Error message now uses `p.Name` instead of `p.Construct.id`, so the user sees the pipeline name they assigned.

Existing `TestBuildReturnsErrorForDuplicateJobNames` (renamed from the Synth version) still covers the direct `Build()` path. Full suite green.
