### PR TITLE
fix: add FetchDepth to IR for round-trip data preservation

### LINKED ISSUE #9: [Bug]: FetchDepth missing from IR — round-trip data loss
### pisyn version

pisyn dev (schema v1)

### Affected platform

GitLab CI

## Problem

`IRJob` in `pkg/pisyn/ir.go` doesn't include `FetchDepth`. Round-tripping through `pipeline.json` (via `pisyn build` → `pisyn graph`/`pisyn run`) loses the fetch depth setting.

## Suggested Fix

Add `FetchDepth int` to `IRJob`, and update `jobToIR()` and `irJobToJob()` to map it.

## Files

- `pkg/pisyn/ir.go` — `IRJob`, `jobToIR()`, `irJobToJob()`

### Expected behavior

FetchDepth gets included in the pipeline.json

### Steps to reproduce

```go

```

### Actual output

```yaml

```

### PR DESCRIPTION
**Pull request by mvanhorn**
`IRJob` was missing `FetchDepth`, so round-tripping through `pipeline.json` (via `pisyn build` followed by `pisyn graph`/`pisyn run`) silently dropped the fetch depth setting.

Added the field to `IRJob` and wired it through `jobToIR()` and `irJobToJob()` in `pkg/pisyn/ir.go`.

Uses `json:"fetch_depth"` without `omitempty` because `0` is a valid value (full history) and `-1` means unset.

Closes #9

### CODE REVIEW

File: pkg/pisyn/ir.go [hunk 1]
```diff
@@ -65,6 +65,7 @@ type IRJob struct {
 	Rules           []Rule              `json:"rules,omitempty"`
 	Interruptible   *bool               `json:"interruptible,omitempty"`
 	Outputs         []JobOutput         `json:"outputs,omitempty"`
+	FetchDepth      int                 `json:"fetch_depth"`
```
Comment (t0st) [inline pkg/pisyn/ir.go]:
```suggestion
	FetchDepth      *int                 `json:"fetch_depth"`
```

**Review by t0st — CHANGES_REQUESTED** [review]
Thx again for your contribution! 💪

One suggestion before merging:

FetchDepth int without omitempty works, but it means Go's zero value (0) and the intentional "full history" value (0) are indistinguishable. If pipeline.json ever lacks the field (partial generation, hand-editing, future 
format changes), it silently defaults to full clone instead of unset.

Would you mind switching to *int with omitempty? That matches the pattern we already use for Interruptible *bool in the same struct:

go
// In IRJob struct:
FetchDepth      *int                `json:"fetch_depth,omitempty"`

// In jobToIR():
FetchDepth:      intPtr(job.FetchDepth),

// In irJobToJob():
FetchDepth:      derefInt(irj.FetchDepth, -1),


With two small helpers:

go
func intPtr(v int) *int { return &v }

func derefInt(p *int, fallback int) int {
    if p == nil {
        return fallback
    }
    return *p
}

Thx!

**Comment by mvanhorn** [comment]
Switched IRJob.FetchDepth to *int in 0790779. Added small helpers (jobFetchDepthToIR/irFetchDepthToJob) that encode Job's -1 sentinel as nil on the way into the IR and restore it on the way out, so the existing unset/0/N semantics round-trip cleanly. Kept json:"fetch_depth" as-is (no omitempty) to match your suggestion. All tests still pass.
